name: Integration ğŸ”„

permissions:
  contents: write
  pull-requests: write

on:
  pull_request:

jobs:
  linelint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ì¤„ë°”ê¿ˆ ì²´í¬
      - name: Check for missing end line breaks
        run: |
          echo "ğŸ” ì¤„ë°”ê¿ˆ ê²€ì‚¬ ì‹œì‘"
          echo "ê¸°ì¤€ ì»¤ë°‹: ${{ github.event.pull_request.base.sha }}"
          echo "í˜„ì¬ ì»¤ë°‹: ${{ github.sha }}"

          files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | tr -d '"')
          target_file_list=()

          echo "ğŸ“ ë³€ê²½ëœ íŒŒì¼ ëª©ë¡:"
          echo "$files"

          echo "## ì¤„ë°”ê¿ˆ ëˆ„ë½ íŒŒì¼" >> $GITHUB_STEP_SUMMARY
          for file in $files; do
            echo "ê²€ì‚¬ ì¤‘: $file"
            if [ -s "$file" ] && [ "$(tail -c 1 $file | wc -l)" -eq 0 ]; then
              # ê°œí–‰ ì¶”ê°€
              echo >> "$file"
              echo "âœï¸ ê°œí–‰ ì¶”ê°€: $file"
              echo "- $file" >> $GITHUB_STEP_SUMMARY
              target_file_list+=("$file")
            else
              echo "âœ… ì •ìƒ: $file"
            fi
          done

          if [ "${#target_file_list[@]}" -gt 0 ]; then
            echo -e "\nìë™ ìˆ˜ì •ëœ íŒŒì¼ ìˆ˜: ${#target_file_list[@]}" >> "$GITHUB_STEP_SUMMARY"
            
            # ìœ ì € ì„¤ì •
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"

            # ë³€ê²½ë¶„ ì»¤ë°‹ & í‘¸ì‹œ
            git add "${fixed_list[@]}"
            git commit -m "chore(ci): add missing trailing newline to files"
            git push

            echo "âœ… ëˆ„ë½ëœ ê°œí–‰ ìë™ ì¶”ê°€ ë° ì»¤ë°‹/í‘¸ì‹œ ì™„ë£Œ"
            exit 1
          else
            echo "âœ… ëª¨ë“  íŒŒì¼ì˜ ì¤„ë°”ê¿ˆ ì •ìƒ"
          fi
